[package]
name = "yew-tinkering-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
material-yew="0.1.0"
yew="0.19.3"
yew-router="0.16.0"
